#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start WM

EXTERNAL_NAME="HDMI-A-0"
INTERNAL_NAME="eDP"

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --output "${EXTERNAL_NAME}" --primary --auto --output "${INTERNAL_NAME}" --right-of "${EXTERNAL_NAME}" --auto

# Set trackpad to support touch
xinput set-prop 12 339 1

# picom &
# nm-applet &
command -v dropbox &>/dev/null && dropbox &
#
# exec awesome
exec xmonad
