#!/bin/sh

if [ -f $HOME/.Xmodmap ]; then
    xmodmap $HOME/.Xmodmap
fi

EXTERNAL_MONITOR="HDMI-A-0"
#EXTERNAL_MONITOR="DisplayPort-0"
EXTERNAL_MONITOR="DisplayPort-1"
xrandr --output ${EXTERNAL_MONITOR} --primary --auto --output "eDP" --right-of ${EXTERNAL_MONITOR} --auto
# feh --bg-fill --recursive --randomize --no-fehbg /usr/share/backgrounds/nordic-wallpapers/
status-notifier-watcher &
nm-applet --indicator &
export XDG_CURRENT_DESKTOP="Unity"
dropbox start
emacs --fg-daemon &
# dwm-statusbar &> /tmp/dwm-statusbar.log &
# exec dwm
taffybar-exe &
exec xmonad-exe
# polybar external &
# exec leftwm
# exec startlxqt
