#!/bin/sh

SXHKD_SHELL=/bin/bash sxhkd &
autorandr --change
xsetroot -cursor_name left_ptr &

picom &
snixembed --fork
~/.config/lemonbar/lemonstart.sh &
pkill stalonetray; stalonetray &
# trayer --edge top --align right --width 125 \
# 	--heighttype pixel --height 20 --transparent true --alpha 50 --tint 0x18191a\
# 	--SetDockType true &

INTERNAL_MONITOR='eDP'
EXTERNAL_MONITOR='DisplayPort-0'

bspc monitor $EXTERNAL_MONITOR -d 1 2 3 4 5
bspc monitor $INTERNAL_MONITOR -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap	         10
bspc config focused_border_color \#ed4b15
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a "Brave-browser" monitor=$INTERNAL_MONITOR
bspc rule -a "Google-chrome" monitor=$INTERNAL_MONITOR
bspc rule -a "Chromium" monitor=$INTERNAL_MONITOR
bspc rule -a "firefox-esr" monitor=$INTERNAL_MONITOR
#bspc rule -a polybar border=off manage=off
#bspc rule -a lemonbar border=off layer=below
bspc rule -a trayer border=off layer=above
bspc rule -a ulauncher focus=on
bspc rule -a "JetBrains Toolbox" state=floating
bspc rule -a skype state=floating
# https://github.com/baskerville/bspwm/issues/291
# only works due to https://github.com/dasJ/spotifywm
bspc rule -a Spotify desktop='0' state=pseudo_tiled


#status-notifier-watcher &
nm-applet --indicator &
blueman-applet &
dropbox start
wmname LG3D &
dunst &
feh --bg-fill --recursive --randomize --no-fehbg /usr/share/backgrounds/nordic-wallpapers/
volctl &
