#! /bin/sh

sxhkd &
ulauncher --hide-window --no-window-shadow &
nm-applet &
xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
# bspc monitor eDP-1-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap	         2
bspc config focused_border_color \#ed4b15
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a "Brave-browser" monitor='eDP-1-1'
bspc rule -a "Google-chrome" monitor='eDP-1-1'
bspc rule -a polybar border=off manage=off
bspc rule -a ulauncher focus=on
bspc rule -a "JetBrains Toolbox" state=floating
bspc rule -a skype state=floating

picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
wmname LG3D &
udiskie &

xrandr --output HDMI-0 --auto --output eDP-1-1 --auto --right-of HDMI-0
